### ISSUE TITLE
Investigate better project structure

### ISSUE THREAD

**Issue by pk400** [Midnight-Cafe/midnight-cafe#6]
I set the app up using `npx create-next-app` and it set up the project structure in a certain way. I am not certain this is the best way to organize files/folders so this ticket is just to see if there is a better way to structure it or if keeping it this way is fine.

**Comment by samfitz13** [comment]
Keeping it this way is fine. there are some unused files that should be pruned though. I can help identify if needed. -sf

**Comment by pk400** [comment]
Sweet, if there is any way we can improve it we'll deal with it on the way. I already like your suggestion in #8. I'll close this for now.
